name: Run Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # every hour

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner
        run: python -m backend.scanner
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
          LUNARCRUSH_API_KEY: ${{ secrets.LUNARCRUSH_API_KEY }}
          MESSARI_API_KEY: ${{ secrets.MESSARI_API_KEY }}
          SANTIMENT_API_KEY: ${{ secrets.SANTIMENT_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_STOCK_CHANNEL_ID: ${{ secrets.TELEGRAM_STOCK_CHANNEL_ID }}
          TELEGRAM_CRYPTO_CHANNEL_ID: ${{ secrets.TELEGRAM_CRYPTO_CHANNEL_ID }}

      - name: Upload log artifact
        uses: actions/upload-artifact@v4   # ✅ upgraded from v3 → v4
        with:
          name: scanner-log
          path: trigger_log.json
