name: Update Dashboard

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 mins
  workflow_dispatch:

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run scanner
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python -m backend.scanner

      - name: Push dashboard
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dashboard.json
          git commit -m "Update dashboard data [skip ci]" || echo "No changes"
          git push https://x-access-token:${GITHUB_PAT}@github.com/${{ github.repository }} HEAD:main
