      - name: Commit dashboard
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f dashboard.json ]; then
            git add -f dashboard.json
            git commit -m "Update dashboard data [skip ci]" || echo "No changes"
            git push
          else
            echo "⚠️ dashboard.json not found, skipping commit"
          fi
