name: Run Scanner

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:         # allows manual trigger

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    env:
      FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run Scanner
        run: python -m backend.scanner

      - name: Commit and push dashboard.json
        if: success() && env.PAT_TOKEN != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dashboard.json
          git commit -m "Update dashboard data [skip ci]" || echo "No changes"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main
